### ISSUE TITLE
meow

### ISSUE THREAD

**Issue by rose-is-gay** [ts03GCZqIsTZtu4/swag_tools#2]
zach is pretty hot

**Comment by Synkstar** [comment]
cat

**Comment by Synkstar** [comment]
![image](https://user-images.githubusercontent.com/26175394/121368220-e7c06880-c908-11eb-9c13-79bf7b8f60a8.png)
is this that dude lmao

**Comment by ts03GCZqIsTZtu4** [comment]
No, it's not.
Patched once again :DD:D

**Comment by Synkstar** [comment]
Patched rose
